source 'https://rubygems.org'
gem "json"
gem "sinatra"
gem "sinatra-contrib"
gem "sinatra-activerecord"
gem "pg"
gem "sqlite3"
gem "omniauth"
gem "omniauth-mendeley_oauth2"
gem "puma"
gem "foreman"
gem "rake"
gem "rack-contrib"
gem "i18n"

gem "rspec"
gem "rack-test"
gem "factory_girl"
